services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001" # [Computer Port] : [Inside Docker Port]
    volumes:
      - ./services/auth-service:/app # Syncs 

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/app
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001 
    depends_on:
      - auth-service